### PR TITLE
Toying with shepherd.js for intro tours

### PR DESCRIPTION
**Pull request by StevenWeathers**
## Description

Toying with [Shepherd.js](https://shepherdjs.dev/) for intro tours

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

### CODE REVIEW

**Comment by scottux** [comment]
this is spiffy.

**Comment by StevenWeathers** [comment]
To avoid being annoying I think a nice call to action lets the user decide if they want a tour.

localhost_8080_storyboards

**Comment by StevenWeathers** [comment]
image

image

**Comment by StevenWeathers** [comment]
I'm going to put this on the back burner as I think it warrants more considerations since it would require a great deal of content tuning to be helpful.

**Pull request closed without merging**
