### PR TITLE
Make CheckOrigin configurable by adding ALLOWED_ORIGINS setting

### PR DESCRIPTION
**Pull request by maxrem**
I've deployed the planning poker application on my server and got this error
```websocket: request origin not allowed by Upgrader.CheckOrigin```

I've tried to solve this by making the origin configurable.

### CODE REVIEW

**Comment by StevenWeathers** [comment]
I'm not sure I understand why this is an issue, if you set your domain it should be your origin.

**Comment by maxrem** [comment]
In nginx the host header has `:443` added to its value. So `www.planning-poker.com != www.planning-poker.com:443`.

So, I fixed it in nginx config. Sorry for the confusion. Closing this

**Comment by StevenWeathers** [comment]
> In nginx the host header has `:443` added to its value. So `www.planning-poker.com != www.planning-poker.com:443`.
> 
> So, I fixed it in nginx config. Sorry for the confusion. Closing this

Good find, I'm open to this config option being added if there is a strong case for it, just wanted to make sure I understood the root issue first.

**Comment by Jaz7Mutant** [comment]
@maxrem How did you fix that in your nginx config?

**Comment by maxrem** [comment]
@Jaz7Mutant

Excuse me for not including the fix. This is what I did. I hope it'll work for you:

Instead of:

```
proxy_set_header Host $host:$server_port;
```

use

```
proxy_set_header Host $host;
```

So remove `$server_port`.

**Comment by Jaz7Mutant** [comment]
Thank you!

**Pull request closed without merging**
