### PR TITLE
Ldap authentication

### PR DESCRIPTION
**Pull request by StevenWeathers**
Thanks @eivindt for your hard work on this feature, I will bring this in so others can take advantage of it ;)

### CODE REVIEW

**Comment by eivindt** [comment]
Hi @StevenWeathers , you're on fire these days, I didn't even make a pull request out of this yet!

I was planning to do some more testing before creating it (I recently did a quite big rebase to get up to date with your changes), and I've already found a couple of merging errors on my part.

I've just committed these to my branch.

**Comment by StevenWeathers** [comment]
@eivindt Yea I've had some free time to focus on Thunderdome the last few days, some big features have been added one of which is Localization.  Can't wait to see how many languages get contributions ;)

Thanks I noticed those small issues as well and already resolved them.

**Comment by eivindt** [comment]
I could add norwegian translations, but I think I'd need to check some old norse inspired battle terms to be able to be in line with the original thunderdome slang.

**Comment by StevenWeathers** [comment]
> I could add norwegian translations, but I think I'd need to check some old norse inspired battle terms to be able to be in line with the original thunderdome slang.

That would be amazing...

**Pull request merged**
