### PR TITLE
Add Portuguese Translations

### PR DESCRIPTION
**Pull request by DanSilva41**
Hi @StevenWeathers,

It's an honor to collaborate with you and with this amazing project.
I opened this simple PR, could you check if I'm doing it right please.

### CODE REVIEW

**Review by StevenWeathers — DISMISSED** [review]

**Comment by StevenWeathers** [comment]
> Hi @StevenWeathers,
> 
> It's an honor to collaborate with you and with this amazing project. I opened this simple PR, could you check if I'm doing it right please.

Yes that's one of the 3 files that would need to be translated, there are locale files in `frontend/public/default` and `frontend/public/friendly` as well.  I will accept any amount of translations you are willing to commit ;)

**Comment by DanSilva41** [comment]
Wonderful, @StevenWeathers!

I really liked your project and proposal and I'm encouraging its use in my teams.
I certainly hope to become a faithful contributor to this project of yours.

**Comment by DanSilva41** [comment]
At this time, I will continue to work on the translations, in this branch ;)

**Comment by DanSilva41** [comment]
@StevenWeathers, I believe I'm done, please validate.

**Comment by StevenWeathers** [comment]
> @StevenWeathers, I believe I'm done, please validate.

Approved, will merge and release with another PR soon.

**Pull request merged**
