### PR TITLE
Fix some issues in support for RTL languages like Farsi

### PR DESCRIPTION
**Pull request by mahdihmb**
Related to #401

### CODE REVIEW

**Comment by mahdihmb** [comment]
@StevenWeathers Hi,
According to tailwind docs, These failures should not happen.

**Comment by StevenWeathers** [comment]
> @StevenWeathers Hi, According to tailwind docs, These failures should not happen.

Which failures?, link to docs?

**Comment by mahdihmb** [comment]
@StevenWeathers 
https://github.com/StevenWeathers/thunderdome-planning-poker/actions/runs/4393742897/jobs/7694838842

**Comment by mahdihmb** [comment]
Link to docs using colon with @apply:
https://tailwindcss.com/docs/reusing-styles#extracting-classes-with-apply

**Comment by StevenWeathers** [comment]
> Link to docs using colon with `@apply`: https://tailwindcss.com/docs/reusing-styles#extracting-classes-with-apply

It's likely something to do with the jest setup, that said I have pushed an update with all these fixes applied including some refactoring of the styles to get around the error.

**Pull request closed without merging**
