### PR TITLE
Add support for deck with Fibonacci numbers, add Coffee card

### PR DESCRIPTION
**Pull request by s4got10dev**
We recently found this tool and find it very useful 🎉 

Although we are relying on Fibonacci deck and use Coffee card, so would appreciate if you will allow this change.

### CODE REVIEW

**Comment by StevenWeathers** [comment]
There is UI code that would need to be updated to exclude the coffee emoji from the average points results
https://github.com/StevenWeathers/thunderdome-planning-poker/blob/master/frontend/src/components/battle/VoteResults.svelte#L26

**Comment by s4got10dev** [comment]
> There is UI code that would need to be updated to exclude the coffee emoji from the average points results https://github.com/StevenWeathers/thunderdome-planning-poker/blob/master/frontend/src/components/battle/VoteResults.svelte#L26

Thanks for pointing out. I've also included handling of coffee emoji for generation of `reversedPoints` array

**Review by StevenWeathers — APPROVED** [review]

**Comment by StevenWeathers** [comment]
> > There is UI code that would need to be updated to exclude the coffee emoji from the average points results https://github.com/StevenWeathers/thunderdome-planning-poker/blob/master/frontend/src/components/battle/VoteResults.svelte#L26
> 
> Thanks for pointing out. I've also included handling of coffee emoji for generation of `reversedPoints` array

Perfect, I will test this tonight and then merge/release.

**Comment by StevenWeathers** [comment]
@s4got10dev ok I found one issue which is the limit on the points database column size is currently set to VARCHAR(3).  You will need to increase this to support emojis, I would just recommend altering the type from VARCHAR(3) to TEXT.

To do this you will need to use the go migrate tool to generate a new DB migration

```
migrate create -ext sql -dir db/migrations alter_plan_points_col_type
```
In the up file you will want
```sql
ALTER TABLE plans ALTER COLUMN points TYPE TEXT;
```
In the down file you will want
```sql
ALTER TABLE plans ALTER COLUMN points TYPE VARCHAR(3);
```

If you have questions or need help with this step I can assist.

**Comment by StevenWeathers** [comment]
@s4got10dev never mind my previous statement I tested in postgres and it doesn't cause an error when you store an emoji in the column.

**Pull request merged**
