### PR TITLE
extend WebSocket origin check to allow APP_DOMAIN

### LINKED ISSUE #522: extend WebSocket origin check to allow APP_DOMAIN
I'm evaluating a self-hosted instance of Thunderdome on Azure Container Apps routed via an Azure Application Gateway.
 This works if I set the APP_DOMAIN configuration correctly, only that the WebSocket origin check fails in this case, as without further configuration, the Host is set to the Container Apps Host and WebSocket Origin is set to the Host/Domain used on the Azure Application Gateway.

I'd suggest allowing the APP_DOMAIN in the origin check as well (but not sure if this would have any adverse side effects).

### PR DESCRIPTION
**Pull request by gwimmel**
## Description

This PR extends the WebSocket origin check by also allowing APP_DOMAIN as origin

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #522

## Steps to QA

Can be tested using a reverse proxy setup (I could provide one if necessary).

### CODE REVIEW

**Comment by gwimmel** [comment]
Here's a first attempt, only for the poker client, which works for my use case. Doesn't allow for subdomains (yet). Can you provide some feedback before I possibly change the other clients? Is there a reason why the value for APP_DOMAIN in the Dockerfile/Makefile starts with "." (i.e., .127.0.0.1), whereas the default doesn't ("thunderdome.dev")?

**Comment by StevenWeathers** [comment]
> Here's a first attempt, only for the poker client, which works for my use case. Doesn't allow for subdomains (yet). Can you provide some feedback before I possibly change the other clients? Is there a reason why the value for APP_DOMAIN in the Dockerfile/Makefile starts with "." (i.e., .127.0.0.1), whereas the default doesn't ("thunderdome.dev")?

So the Makefile commands are for local development, I've actually got a PR in motion to do auth and I've changed the `.127.0.0.1` to localhost and things seem to continue to function, I had issues at one point with localhost and cookies or something however it seems to be working just fine now.  As far as defaults go they're just that, defaults for convenience and expected to be changed per installation in real environments.

**Review by StevenWeathers — APPROVED** [review]

**Comment by StevenWeathers** [comment]
I tested this locally and it seems to work just fine, I would suggest just copy pasting the logic to each respective features websocket code for now as there is another ticket for abstraction which will introduce an `internal/websocket` package for all the common parts.

**Review by scottux — DISMISSED** [review]

**Comment by gwimmel** [comment]
> I tested this locally and it seems to work just fine, I would suggest just copy pasting the logic to each respective features websocket code for now as there is another ticket for abstraction which will introduce an `internal/websocket` package for all the common parts.

Great. I've copied the logic to the other features, please take another look.

**Comment by gwimmel** [comment]
> > Here's a first attempt, only for the poker client, which works for my use case. Doesn't allow for subdomains (yet). Can you provide some feedback before I possibly change the other clients? Is there a reason why the value for APP_DOMAIN in the Dockerfile/Makefile starts with "." (i.e., .127.0.0.1), whereas the default doesn't ("thunderdome.dev")?
> 
> So the Makefile commands are for local development, I've actually got a PR in motion to do auth and I've changed the `.127.0.0.1` to localhost and things seem to continue to function, I had issues at one point with localhost and cookies or something however it seems to be working just fine now. As far as defaults go they're just that, defaults for convenience and expected to be changed per installation in real environments.

Thanks for the explanation. I mainly wondered about the leading "." (i.e., ".127.0.0.1", not "127.0.0.1", which would have been what I'd have expected).

**Review by StevenWeathers — APPROVED** [review]

**Comment by StevenWeathers** [comment]
Run `goimports -w .`

**Review by StevenWeathers — APPROVED** [review]

**Pull request merged**
